k9s:
  cluster: datascience
  namespace:
    active: peter-gaultney
    lockFavorites: true
    favorites:
    - peter-gaultney
    - unified-directory
    - visits-api
    - tim-blass
    - grant-andersen
    - caleb-gregory
    - ben-cornelis
    - matt-eby
    - unified-asset
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
